# Define skeleton as (keypoint: parent) pairs.
# Key-value types must be the same, either int or str
# The parent of the root node is itself
skeleton:
  SpineF: SpineF
  HeadB: SpineF
  HeadF: SpineF
  HeadL: SpineF
  ShoulderL: SpineF
  ElbowL: ShoulderL
  ArmL: ElbowL
  ShoulderR: SpineF
  ElbowR: ShoulderR
  ArmR: ElbowR
  SpineM: SpineF
  SpineL: SpineM
  HipL: SpineL
  KneeL: HipL
  ShinL: KneeL
  HipR: SpineL
  KneeR: HipR
  ShinR: KneeR

# # Full skeleton (K=20)
# skeleton:
#   SpineF: SpineF
#   HeadB: SpineF
#   HeadF: SpineF
#   HeadL: SpineF
#   ShoulderL: SpineF
#   ElbowL: ShoulderL
#   ArmL: ElbowL
#   ShoulderR: SpineF
#   ElbowR: ShoulderR
#   ArmR: ElbowR
#   SpineM: SpineF
#   Offset1: SpineM
#   SpineL: SpineM
#   Offset2: SpineL
#   HipL: SpineL
#   KneeL: HipL
#   ShinL: KneeL
#   HipR: SpineL
#   KneeR: HipR
#   ShinR: KneeR
